events {}

http {
    upstream auth_service {
        server autenticacion-tenant:5000;
    }

    upstream integraciones_service {
        server integraciones:5000;
    }

    upstream perfil_service {
        server perfil-financiero:5000;
    }

    upstream scoring_service {
        server scoring-recomendador:5000;
    }

    server {
        listen 80;
        server_name localhost;

        location /api/auth/ {
            proxy_pass http://auth_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/integraciones/ {
            proxy_pass http://integraciones_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/perfiles/ {
            proxy_pass http://perfil_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/scoring/ {
            proxy_pass http://scoring_service/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}