"""Initial migration: create tables

Revision ID: 2299add10364
Revises: 
Create Date: 2026-04-13 01:15:14.212993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2299add10364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_necesidades', schema=None) as batch_op:
        batch_op.alter_column('documento_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('etiqueta_interes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('fuente_data',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('analisis_necesidades_documento_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('datos_financieros_limpios', schema=None) as batch_op:
        batch_op.alter_column('documento_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('comportamiento_pagos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('instituciones', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('nombre_fintech',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('perfiles_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.Integer(), nullable=True))
        batch_op.alter_column('documento_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('id_institucion',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('nombre_completo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('educacion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('estado_civil',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfiles_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('estado_civil',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('educacion',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_completo',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id_institucion',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               nullable=True)
        batch_op.alter_column('documento_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('sexo')

    with op.batch_alter_table('instituciones', schema=None) as batch_op:
        batch_op.alter_column('nombre_fintech',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('datos_financieros_limpios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('comportamiento_pagos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('documento_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('analisis_necesidades', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('analisis_necesidades_documento_id_fkey'), 'perfiles_clientes', ['documento_id'], ['documento_id'])
        batch_op.alter_column('fuente_data',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('etiqueta_interes',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('documento_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
